name: VocalMimicryMenu
version: '${project.version}'
main: com.strangeone101.vocalmimicrymenu.VocalMimicryMenu
api-version: 1.15
depend: [ ProjectKorra, ProjectAddons]
authors: [ StrangeOne101]
description: An interactive menu to change the sound used in VocalMimicry
commands:
  vocalmenu:
    description: Open the VocalMimicryMenu
    aliases: [vcl, vocamimi, vocalmimicrymenu]
    permission: bending.command.vocalmenu

